import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./components/Provider";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {/* HomePage is children */}
          <main className="px-4 md:px-12 lg:px-16 xl:px-20">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
